### ISSUE TITLE
Compliment!

### ISSUE THREAD

**Issue by PipHarsveld** [Inevdhoven/real-time-web-2223#16]
Wanneer je een foute gok maakt voor de titel van het boek, wordt het plaatje steeds duidelijker zichtbaar totdat je het te vaak fout hebt en dan ben je gameover. Ik vind dit zo enorm leuk gedaan! Hierdoor wordt het raden van de boeken steeds wat makkelijker :D

**Comment by Inevdhoven** [comment]
Dankjewel!!! :)
