### ISSUE TITLE
Functie van dikgedrukte naam?

### ISSUE THREAD

**Issue by PipHarsveld** [Inevdhoven/real-time-web-2223#17]
Het is voor mij niet helemaal duidelijk wat de functie is van de dikgedrukte naam? Ik dacht eerst dat dat dan aangeeft wat jouw naam is en dat de nicknames van anderen niet dikgedrukt waren, maar als dit het geval is werkt het niet helemaal lekker. Het zou ook nog kunnen zijn dat het aangeeft wie actief is en de chat en wie niet, maar dat is voor mij niet zo duidelijk.

![image](https://github.com/Inevdhoven/real-time-web-2223/assets/54938035/1be14eec-639e-439d-a064-c013ea4c3be6)

**Comment by Inevdhoven** [comment]
Dit is opgelost, het lang aan de history, deze krijgen niet de juiste ids mee.
