### ISSUE TITLE
Info API key

### ISSUE THREAD

**Issue by PipHarsveld** [Inevdhoven/real-time-web-2223#20]
Bij installeren van het project heb je een stukje beschreven over het krijgen van een API key. Ik zou deze informatie ook nog bij het hoofdstuk over de API zelf zetten, zodat je de informatie ook ziet als je alleen de API info bekijkt.

Dit stukje:
![image](https://github.com/Inevdhoven/real-time-web-2223/assets/54938035/c87cfff2-e129-47d6-aaf1-7cd6a1ba9b55)

**Comment by Inevdhoven** [comment]
Ik heb dit nu ook toegevoegd aan de readme
