### ISSUE TITLE
Groter plaatje

### ISSUE THREAD

**Issue by EvaZ7** [Inevdhoven/real-time-web-2223#21]
Ik zou het plaatje groter maken van het boek zo is het beter leesbaar en ligt daar meer de focus voor de gebruiker

**Comment by Inevdhoven** [comment]
De afbeeldingen in de API zijn helaas erg klein waardoor als ik ze groter zou maken deze erg wazig worden. Daarom heb ik ervoor gekozen ze zo te houden.
